#!/usr/bin/env ruby

def prepend_message
  branch = `git rev-parse --abbrev-ref HEAD`
  acunote_task = branch.match(/acu[0-9]+/)
  jira_task    = branch.match(/IV-[0-9]+/)

  return unless acunote_task || jira_task

  if acunote_task
    reference = "#{acunote_task} "
  else
    reference = "#{jira_task} "
  end

  old_msg = File.read ARGV[0]

  unless old_msg.match(reference)
    File.open ARGV[0], 'w' do |new_msg|
      new_msg.write reference + old_msg
    end
  end
end

prepend_message
