#!/usr/bin/env ruby

def prepend_message
  branch = `git rev-parse --abbrev-ref HEAD`
  acunote_match  = branch.match(/acu[0-9]+/)

  return unless acunote_match
  acunote_id = acunote_match[0]

  old_msg = File.read ARGV[0]

  unless old_msg.match(/^#{acunote_id}/)
    File.open(ARGV[0], 'w') do |fh|
      fh.write("#{acunote_id} #{old_msg}")
    end
  end
end

prepend_message
